### ISSUE TITLE
Segmentation violation in several CLI commands

### ISSUE THREAD

**Issue by antoineco** [unikraft/kraftkit#367]
### Describe the bug

Running `kraft fetch`, `kraft prepare`, `kraft menu` or `kraft clean` inside the `app-helloworld` repo yields the following segfault:

```console
$ kraft fetch
[ W ] could not initialize package manager: could not determine handler [format]=oci
[ W ] could not read target config file: could not open file: open /home/acotten/git/unikraft/app-helloworld/.config.helloworld_linuxu-x86_64: no such file or directory
[ W ] could not read target config file: could not open file: open /home/acotten/git/unikraft/app-helloworld/.config.helloworld_kvm-x86_64: no such file or directory
[ W ] could not read target config file: could not open file: open /home/acotten/git/unikraft/app-helloworld/.config.helloworld_xen-x86_64: no such file or directory
[ W ] could not read target config file: could not open file: open /home/acotten/git/unikraft/app-helloworld/.config.helloworld_linuxu-arm64: no such file or directory
[ W ] could not read target config file: could not open file: open /home/acotten/git/unikraft/app-helloworld/.config.helloworld_kvm-arm64: no such file or directory
[ W ] could not read target config file: could not open file: open /home/acotten/git/unikraft/app-helloworld/.config.helloworld_linuxu-arm: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xfb8536]

goroutine 1 [running]:
kraftkit.sh/unikraft/app.application.MakeArgs({{0xc00033b1f0, 0xa}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc0000460c4, 0x29}, ...}, ...)
        /home/acotten/git/unikraft/kraftkit/unikraft/app/application.go:301 +0x796
kraftkit.sh/unikraft/app.application.Make({{0xc00033b1f0, 0xa}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc0000460c4, 0x29}, ...}, ...)
        /home/acotten/git/unikraft/kraftkit/unikraft/app/application.go:317 +0x20a
kraftkit.sh/unikraft/app.application.Fetch({{0xc00033b1f0, 0xa}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc0000460c4, 0x29}, ...}, ...)
        /home/acotten/git/unikraft/kraftkit/unikraft/app/application.go:434 +0x1a5
kraftkit.sh/cmd/kraft/fetch.(*Fetch).Run(0x0?, 0x0?, {0x2732a80?, 0x0?, 0x0?})
        /home/acotten/git/unikraft/kraftkit/cmd/kraft/fetch/fetch.go:67 +0xda
kraftkit.sh/cmdfactory.bind.func1(0xc000004f00?, {0x2732a80, 0x0, 0x0})
        /home/acotten/git/unikraft/kraftkit/cmdfactory/builder.go:431 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc000004f00, {0x2732a80, 0x0, 0x0})
        /home/acotten/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004600)
        /home/acotten/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/acotten/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/acotten/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
kraftkit.sh/cmdfactory.Main({0x1d09688?, 0xc000542150}, 0xc000004600)
        /home/acotten/git/unikraft/kraftkit/cmdfactory/builder.go:103 +0x73
main.main()
        /home/acotten/git/unikraft/kraftkit/cmd/kraft/kraft.go:142 +0x3a5
```

**Comment by antoineco** [comment]
The issue is here:

https://github.com/unikraft/kraftkit/blob/16f905f9e3831421b26d19a6cdeabf8393e06112/unikraft/app/application.go#L301

When I execute any of the commands listed above, `func (application) MakeArgs` receives `tc` with the value `kraftkit.sh/unikraft/target.Target nil` as argument.

This is very much expected because commands pass an explicit `nil`:

https://github.com/unikraft/kraftkit/blob/16f905f9e3831421b26d19a6cdeabf8393e06112/cmd/kraft/clean/clean.go#L90

**Comment by antoineco** [comment]
The culprit: c640b12bf700129d5fd8a18ca172434750deebb3
