### ISSUE TITLE
Kraft v0.7.0 fails on Apple Silicon (Sonoma)

### ISSUE THREAD

**Issue by jviotti** [unikraft/kraftkit#994]
### Describe the bug

```
$ kraft fetch --log-type=basic
 W  specification in Kraftfile (v0.5) version is not latest (v0.6)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105182354]

goroutine 1 [running]:
kraftkit.sh/internal/cli/kraft/fetch.(*FetchOptions).pull(0x14000415c00, {0x1058affb8, 0x14000287350}, {0x1058c6058, 0x1400031bb00}, {0x16bc4f31d, 0x8}, 0x1, 0xffffffffffffffff)
        /__w/kraftkit/kraftkit/internal/cli/kraft/fetch/fetch.go:216 +0x674
kraftkit.sh/internal/cli/kraft/fetch.(*FetchOptions).Run(0x14000415c00, {0x1058affb8, 0x14000287350}, {0x0?, 0x0?, 0x0?})
        /__w/kraftkit/kraftkit/internal/cli/kraft/fetch/fetch.go:384 +0x17c
kraftkit.sh/cmdfactory.New.func1(0x0?, {0x140001a92a0?, 0x0?, 0x0?})
        /__w/kraftkit/kraftkit/cmdfactory/builder.go:365 +0x4c
kraftkit.sh/cmdfactory.AttributeFlags.bind.func3(0x14000235a00?, {0x140001a92a0, 0x1, 0x2})
        /__w/kraftkit/kraftkit/cmdfactory/builder.go:547 +0x150
github.com/spf13/cobra.(*Command).execute(0x14000160c00, {0x140001a9280, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x14000160000)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
kraftkit.sh/cmdfactory.Main({0x1058affb8?, 0x140003a2f60}, 0x14000160000)
        /__w/kraftkit/kraftkit/cmdfactory/builder.go:183 +0x70
kraftkit.sh/internal/cli/kraft.Main({0x16bc4f300?, 0x1041eb6e0?, 0x10647d228?})
        /__w/kraftkit/kraftkit/internal/cli/kraft/kraft.go:165 +0x51c
main.main()
        /__w/kraftkit/kraftkit/cmd/kraft/main.go:19 +0x94
make: *** [unikraft] Error 2
```

### Steps to reproduce

Run `Kraft fetch`

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

macOS

**Comment by craciunoiuc** [comment]
People really like `kraft fetch` :sweat_smile: 

Hey @jviotti, the last thing we did before `0.7.0` was to hide `kraft fetch` because it requires some significant rework.

If you want to just pull sources you can start a build a stop when building starts

**Comment by craciunoiuc** [comment]
If you want to pull stuff, you can use `kraft pkg pull`

**Comment by jviotti** [comment]
Sounds good. I'll stop using `fetch`!

**Comment by craciunoiuc** [comment]
Okay, let me know if it worked :pray:

**Comment by jviotti** [comment]
Works! If `fetch` shouldn't be used anymore (and it's currently broken), maybe worth removing it to avoid confusion? Feel free to close this issue anyway

**Comment by craciunoiuc** [comment]
Yeah, considering we want to rework it, it is just hidden.

I will keep the Issue open till we add a `deprecated` warning for these types of commands
